name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: Cache SBT ivy cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Set up Ruby 2.6 (for microsite)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install microsite dependencies
        run: |
          bundle install --system --gemfile=site/Gemfile

      - name: Compile and test
        run: |
          sbt ci

#      - uses: actions/upload-artifact@v1
#        with:
#          name: my-artifact
#          path: path/to/artifact
